import { existsSync, readFileSync, writeFileSync } from 'node:fs';

const directory='artifacts/m7',capture='browser-final';
const states=JSON.parse(readFileSync(`${directory}/${capture}/capture-states.json`,'utf8'));
const detail=JSON.parse(readFileSync(`${directory}/detail-final/evidence.json`,'utf8'));
const motion=JSON.parse(readFileSync(`${directory}/motion/evidence.json`,'utf8'));
const clear=JSON.parse(readFileSync(`${directory}/stress/clear-day-binding-fix/stress-report.json`,'utf8'));
const rain=JSON.parse(readFileSync(`${directory}/stress/rain-dusk-binding-fix/stress-report.json`,'utf8'));
const timing=[['Clear / day',clear],['Rain / dusk',rain]].map(([name,report])=>({name,
  transitionMax:Math.max(...report.endpoints.map(e=>e.measurement.transitions.transitionSpecificMaximumMs)),
  p95:report.endpoints.map(e=>e.measurement.p95.toFixed(1)).join(' / '),
  retainedHeap:report.endpoints.map(e=>(e.retainedHeap.used/1e6).toFixed(2)).join(' → '),
  sha256:report.runtimeSourceSha256}));
states['central-market-hero']=detail.states['central-market-hero'];
states['lower-canal-hero-close']=detail.states['lower-canal-hero'];
const river='../m5-1/market-regression';
const conditions={};
for(const [id,s] of Object.entries(states))conditions[id]={backend:s.facts.backend,feet:s.state.player.position,
  mode:s.state.camera.mode,weather:s.state.environment.weather,light:s.state.environment.timeOfDay,camera:s.camera,
  viewport:s.render.viewport,resets:s.state.resets,active:s.streaming.activeIds,npcTiers:s.npcTiers,method:s.captureMethod??'Native WebGPU authored bookmark after continuous route proof'};
const views=[['eagle-eye','eagle-eye'],['street','primary-street'],['alley','first-person-alley'],['hero','guild-hall'],
  ['day','primary-street'],['night','night'],['rain','rain'],['doorway','first-person-doorway'],['transition','rural-connection'],
  ['dock','quay-service'],['quay',null],['bridge',null],['hero-close',null],['repetition-diagnostics',null]];
const available=views.map(([view,riverView])=>({view,river:riverView&&existsSync(`${directory}/${river}/${riverView}.png`)?`${river}/${riverView}.png`:null,
  districts:['central-market','lower-canal'].map(id=>({id,path:view==='hero'&&id==='central-market'||view==='hero-close'&&id==='lower-canal'?`detail-final/${id}-hero.png`:existsSync(`${directory}/${capture}/${id}-${view}.png`)?`${capture}/${id}-${view}.png`:null}))}));
const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Cpath fill='%23b5cbb1' d='M4 25V11L16 3l12 8v14H4Z'/%3E%3C/svg%3E"><title>M7 — two urban districts</title>
<style>:root{color-scheme:dark;font:15px/1.5 system-ui;background:#17231f;color:#e9e1cc}body{margin:0}header,main{padding:24px 30px}header{border-bottom:1px solid #526655}h1{font:34px Georgia;margin:6px 0}.tag{letter-spacing:.14em;font-size:11px;color:#b5cbb1}a{color:#c2d9b9}nav{display:flex;gap:12px;flex-wrap:wrap;align-items:center}button,select{font:inherit;padding:9px 13px;background:#2e4135;border:1px solid #6e876f;color:inherit}.comparison{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:20px}figure{margin:0}img{width:100%;background:#263b2c;object-fit:contain}figcaption{color:#b9cbb0}pre{white-space:pre-wrap;font:12px/1.5 monospace;max-height:240px;overflow:auto}.risk{color:#dfc9aa}details{margin:18px 0}table{border-collapse:collapse}td,th{padding:8px 18px 8px 0;text-align:left;border-bottom:1px solid #4d6251}@media(max-width:1000px){.comparison{grid-template-columns:1fr}header,main{padding:20px}}</style>
<header><div class="tag">M7 · HUMAN REVIEW GATE</div><h1>Exchange streets & working canal</h1><p>Central Market: 68 buildings, 15 stalls, 32 new locals. Lower Canal: 55 buildings, 2 stalls, 20 new locals and a connected timber cargo dock. The fourteen-district M6.1 macro layout and accepted rural/River Market are preserved.</p><a href="/?scene=m7">Play M7</a> · <a href="../../STATUS.md">Status and measured limits</a> · <a href="${capture}/capture-states.json">Exact capture states</a></header>
<main><nav><button id="prev">← Previous</button><label>View <select id="view"></select></label><button id="next">Next →</button></nav><div class="comparison" id="images"></div><p id="caption"></p><details><summary>Recorded candidate conditions</summary><pre id="conditions"></pre></details>
<details><summary>Approach from the accepted River Market</summary><img src="${capture}/accepted-river-market-transition.png" alt="Accepted River Market transition on the continuous M7 route"><p>The accepted district remains part of the natural-spawn approach. The native route proof records its traversal before either production district.</p></details>
<details><summary>Original city master</summary><img src="../../docs/reference/city-master.png" alt="Original master reference"><p>Composition and palette authority. Different cameras and incomplete unseen details prevent a pixel-match claim.</p></details>
<p class="risk">Review limits: the other city districts remain macro proxies; street walls and banks retain orderly runs; shared kit carpentry, closed entrances and the diagnostic player capsule remain visible. Candidate views use explicit bookmark setup, separately from continuous route proof and actual-input streaming timing. River Market comparison is the accepted M5.1 capture, with different camera poses and footprint.</p>
<details open><summary>Measured streaming and lifecycle findings</summary><table><tr><th>Latest preset</th><th>p95, two circuits (ms)</th><th>Transition maximum (ms)</th><th>GC-retained returns (MB)</th></tr>${timing.map(t=>`<tr><td>${t.name}</td><td>${t.p95}</td><td>${t.transitionMax.toFixed(1)}</td><td>${t.retainedHeap}</td></tr>`).join('')}</table><p>Actual W/Shift input, 1920×1080 / DPR1, initialized RX 6950 XT WebGPU. All four circuits pass the local &lt;200 ms transition-tail assertion, with zero recovery resets/errors and exact equivalent owned-resource returns. Browser wall intervals and JavaScript heap are separate from GPU time and VRAM. The earlier source recorded a 231.3 ms transition-window interval and repeated binding-cache heap growth. The pinned lifecycle adapter removes the observed binding/uniform accumulation in the clear endpoint graphs; the remaining 0.76/1.01 MB heap rises are not fully attributed. The earlier gap's cause remains unestablished. Total-heap plateau and longer-soak stability are unmeasured. <a href="../../docs/PERFORMANCE_BUDGETS.md">Performance budgets</a> retain failed evidence and all limits.</p><pre>${timing.map(t=>`${t.name}: ${t.sha256}`).join('\n')}</pre></details>
<details><summary>Watch human-scale moving review excerpts</summary><div class="comparison">${motion.clips.map(c=>`<figure><figcaption>${c.id} · ${c.name} · ${c.mode} · ${(c.recordedDurationMs/1000).toFixed(1)} s</figcaption><video controls preload="none" style="width:100%" src="motion/${c.id}-${c.name}.webm"></video></figure>`).join('')}</div><p>Actual W input follows declared local setup in each clip. The cargo-stairs setup has one recorded setup reset; no clip adds a recovery reset during movement. These clips, supplementary first-person heroes and local audio precede the binding lifecycle adapter; their source hashes remain in the raw evidence. District content is unchanged, and the native gallery views are refreshed after the adapter. Capture/encoding overhead is excluded from the separate traversal timing.</p><a href="motion/evidence.json">Exact motion states and setup provenance</a></details>
<details><summary>Listen to local day, night and rain ambience</summary><div class="comparison">${detail.audio.map(a=>`<figure><figcaption>${a.district} · ${a.weather} / ${a.light} · ${a.seconds} s</figcaption><audio controls preload="none" src="detail-final/${a.district}-${a.weather}-${a.light}.webm"></audio></figure>`).join('')}</div><p>Stationary recordings from the shared audio context after an actual Explore gesture. Walking and interaction cues are exercised separately in traversal.</p></details>
<p><a href="${capture}/traversal.json">Native WebGPU route proof</a> · <a href="${capture}/webgl2.json">Explicit WebGL2 local circuits</a> · <a href="checks/simulation-binding-fix-suite.json">Latest simulation suite</a> · <a href="checks/browser-binding-fix-suite.json">Latest headed browser suite</a> · <a href="quay-handoff/probe.json">Actual-input quay exit/reentry before binding adapter</a> · <a href="detail-final/evidence.json">Hero/audio evidence</a> · <a href="stress/clear-day-binding-fix/stress-report.json">Latest clear/day timing</a> · <a href="stress/rain-dusk-binding-fix/stress-report.json">Latest rain/dusk timing</a> · <a href="checks/heap-graphs-binding-fix-summary.json">Updated heap graph counts</a> · <a href="checks/binding-retainers-binding-fix.json">Updated binding ownership</a> · <a href="checks/binding-retainers-evidence.json">Earlier heap cache ownership</a> · <a href="stress/clear-day/stress-report.json">Earlier 231.3 ms failure</a></p><p class="tag">Owner art and feel decision pending · stop here before M8</p></main>
<script>const views=${JSON.stringify(available)},conditions=${JSON.stringify(conditions)};const select=document.getElementById('view');views.forEach((v,i)=>select.add(new Option(v.view.replaceAll('-',' '),i)));function show(index){index=(index+views.length)%views.length;select.value=index;const v=views[index],items=[{id:'River Market · accepted M5.1',path:v.river},...v.districts];const images=document.getElementById('images');images.replaceChildren();for(const item of items){const f=document.createElement('figure'),c=document.createElement('figcaption');c.textContent=item.id;f.append(c);if(item.path){const im=new Image();im.src=item.path;im.alt=item.id+' '+v.view;f.append(im)}else{const p=document.createElement('p');p.textContent='No corresponding authored view';f.append(p)}images.append(f)}document.getElementById('caption').textContent='Actual runtime captures. Compare district identity, scale and use of space; these are different authored cameras.';document.getElementById('conditions').textContent=JSON.stringify(Object.fromEntries(v.districts.map(d=>[d.id,conditions[d.id+'-'+v.view]??null])),null,2)}select.onchange=()=>show(+select.value);document.getElementById('prev').onclick=()=>show(+select.value-1);document.getElementById('next').onclick=()=>show(+select.value+1);show(0)</script></html>`;
writeFileSync(`${directory}/review.html`,html);console.log(`Saved ${directory}/review.html with ${views.length} review comparisons.`);
