import {readFileSync,writeFileSync,existsSync} from 'node:fs';
import assert from 'node:assert/strict';
import {runtimeSourceSnapshot} from './runtime-source-snapshot.mjs';
import {upperReviewPaths} from './upper-review-paths.mjs';
const {root,paths,sourceSha256}=upperReviewPaths(),source=runtimeSourceSnapshot();
if(sourceSha256)assert.equal(sourceSha256,source.sha256);
assert(!existsSync(`${root}/${paths.output}`),'Preserve existing review; select a fresh output path.');
const read=p=>JSON.parse(readFileSync(`${root}/${p}`,'utf8'));
const audit=read(paths.audit),captures=read(`${paths.browser}/capture-states.json`),motion=read(`${paths.motion}/evidence.json`);
const waterfront=read(`${paths.waterfront}/capture-states.json`);
const sightlines=read(`${paths.sightlines}/capture-states.json`);
for(const record of [audit,captures,motion,waterfront,sightlines])assert.equal(record.sourceSha256,source.sha256);
assert.equal(Object.keys(waterfront.states).length,2);
assert.equal(Object.keys(sightlines.states).length,12);
const runs=process.argv.slice(2).map(path=>{
  const r=read(`${path}/stress-report.json`);assert.equal(r.runtimeSourceSha256,source.sha256);assert.equal(r.cycles,3);
  return {name:`${r.environmentPreset.weather}-${r.environmentPreset.light}`,districts:r.baseline.city.districts,
    externalWorkloads:r.execution.externalWorkloads,
    points:r.checkpoints.map(c=>({time:c.elapsedMs,cycle:c.cycle,position:c.state.player.position,active:c.streaming.activeIds,
      loaded:c.streaming.loadedIds,tiers:c.npcTiers.counts,mode:c.state.camera.mode}))};
});assert.equal(runs.length,2);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const imageRecords=[[paths.browser,captures],[paths.waterfront,waterfront],[paths.sightlines,sightlines]].flatMap(([folder,record])=>
  Object.keys(record.states).map(name=>({folder,name})));
const images=imageRecords.map(({folder,name})=>`<figure><a href="${folder}/${esc(name)}.png"><img loading="lazy" src="${folder}/${esc(name)}.png" alt="${esc(name)}"></a><figcaption>${esc(name.replaceAll('-',' '))}</figcaption></figure>`).join('');
const videos=motion.clips.map(c=>`<figure><video controls muted preload="metadata" src="${esc(paths.motion)}/${esc(c.id)}-${esc(c.name)}.webm"></video><figcaption>${esc(c.name)} · ${esc(c.mode)} · ${(c.recordedDurationMs/1000).toFixed(1)} s actual input</figcaption></figure>`).join('');
const metrics=audit.runs.flatMap(r=>r.cycles.map(c=>`<tr><td>${esc(r.preset.weather+'/'+r.preset.light)}</td><td>${c.cycle+1}</td>${[c.p50,c.p95,c.p99,c.max,c.transitionMaximum,c.largestPreparationJobMs].map(n=>`<td>${n.toFixed(1)}</td>`).join('')}<td>${(c.retainedHeap.used/1048576).toFixed(1)} MiB</td></tr>`)).join('');
const workloadNotes=[...new Set(runs.map(r=>r.externalWorkloads))];
assert(workloadNotes.every(note=>typeof note==='string'&&note.length>0));
const data=JSON.stringify(runs).replaceAll('<','\\u003c');
writeFileSync(`${root}/${paths.output}`,`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Voxarrium M9 review</title>
<style>body{background:#111e20;color:#e1ddcf;font:16px/1.55 system-ui;margin:auto;padding:32px;max-width:1500px}h1,h2{color:#faf1d7}a{color:#98d3c6}.lead{max-width:1000px}.gallery{display:grid;grid-template-columns:repeat(auto-fit,minmax(330px,1fr));gap:18px}figure{margin:0;background:#203133;padding:10px;border-radius:8px}img,video{width:100%;max-height:550px;object-fit:contain}figcaption{padding:6px}table{border-collapse:collapse;width:100%;font-variant-numeric:tabular-nums}td,th{padding:8px;border-bottom:1px solid #47605f;text-align:left}.route{display:grid;grid-template-columns:minmax(300px,650px) 1fr;gap:20px}svg{width:100%;max-height:700px;background:#1a2e30;border-radius:8px}#time{width:100%}button,select{font:inherit;padding:8px;background:#304b4b;color:#eee;border:1px solid #688f86;border-radius:5px}pre{white-space:pre-wrap}code{overflow-wrap:anywhere}@media(max-width:750px){.route{display:block}.metrics{overflow:auto}}</style>
<h1>Voxarrium M9 · upper city and citadel</h1><p class="lead">Agentic evidence for the preserved core plus Noble Quarter, Temple Quarter, Upper City and deliberate Blender citadel. Human art review is deferred until M10 completes. These local captures and recorded observations describe one frozen runtime; they do not declare final game completion.</p>
<p>Runtime SHA-256: <code>${source.sha256}</code>. Actual headless native WebGPU routes at 1920×1080/DPR1. ${workloadNotes.map(esc).join(' ')} Gameplay captures use 1440×900; canonical eagle-eye uses 900×1500.</p>
<h2>Master composition reference</h2><p>The original artwork remains the composition authority. Canonical game captures below use the accepted deterministic camera and mixed residency; they are not a claim of a completed master footprint or owner acceptance.</p><figure><a href="../../docs/reference/city-master.png"><img src="../../docs/reference/city-master.png" alt="Original master city composition"></a><figcaption>Original master · reference pixels remain outside shipped public assets</figcaption></figure>
<h2>Continuous route observations</h2><p>Playback interpolates saved ten-second observations; this map is evidence navigation, separate from the recorded videos and cadence samples.</p>
<div class="route"><svg id="map" viewBox="-210 -725 660 900"><g id="districts"></g><polyline id="path" fill="none" stroke="#aaa18b" stroke-width="2"/><circle id="player" r="7" fill="#fff1bb" stroke="#162528" stroke-width="2"/></svg><div><select id="preset"></select> <button id="play">Play</button> <button id="reset">Reset</button><input id="time" type="range" min="0" step="1000" value="0"><pre id="state"></pre><p>Two detail leases remain bounded. Stable resource returns and six circuits are documented in the audit; total JS heap growth and the unproven long-soak plateau remain explicit limitations.</p></div></div>
<h2>Native frame intervals</h2><div class="metrics"><table><thead><tr><th>Preset</th><th>Circuit</th><th>p50 ms</th><th>p95 ms</th><th>p99 ms</th><th>Max ms</th><th>Transition max ms</th><th>Largest job ms</th><th>Retained JS heap</th></tr></thead><tbody>${metrics}</tbody></table></div>
<h2>Moving gameplay excerpts</h2><p>Explicit supported setups followed by actual W input. Video recording adds overhead and is excluded from cadence measurement. Full continuity and state preservation are tested on the separate natural-spawn circuits.</p><div class="gallery">${videos}</div>
<h2>Three-view visual inspection</h2><p>Distant districts retain resident coarse architecture while at most two wards show detailed content. Click an image for its full resolution. Source and camera/player/environment/resource states accompany these images in <a href="${esc(paths.browser)}/capture-states.json">capture metadata</a>.</p><div class="gallery">${images}</div>
<p>The two bank service views use separate supported inspection setups. Their exact authored platform and player/resource states are in <a href="${esc(paths.waterfront)}/capture-states.json">waterfront metadata</a>; explicit setup teleports are excluded from natural-route evidence.</p>
<p>Twelve supported public lower-city views include eight first-person positions and four matching third-person views, supplementing the default, locally occluded bookmarks. Their positions, look targets and setup counters are in <a href="${esc(paths.sightlines)}/capture-states.json">sightline metadata</a>. Every street need not see the castle; these pixels document the available orientation views.</p>
<script>const runs=${data};const select=document.querySelector('#preset'),slider=document.querySelector('#time'),state=document.querySelector('#state');let playing=false,playhead=0,last=0;
runs.forEach((r,i)=>{const o=document.createElement('option');o.value=i;o.textContent=r.name;select.append(o)});
const el=(tag,attrs)=>{const e=document.createElementNS('http://www.w3.org/2000/svg',tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));return e};
function show(){const r=runs[+select.value],p=r.points;slider.max=p.at(-1).time;const t=Math.min(playhead,+slider.max);slider.value=t;let i=0;while(i+1<p.length&&p[i+1].time<=t)i++;const a=p[i],b=p[Math.min(i+1,p.length-1)],f=b.time===a.time?0:(t-a.time)/(b.time-a.time);const x=a.position.x+(b.position.x-a.position.x)*f,z=a.position.z+(b.position.z-a.position.z)*f;
const groups=document.querySelector('#districts');groups.replaceChildren();r.districts.forEach(d=>{groups.append(el('polygon',{points:d.footprint.map(q=>q.x+','+q.z).join(' '),fill:a.active.includes(d.id)?'#4b8878':'#334b48',stroke:'#688077','stroke-width':1}));const label=el('text',{x:d.center.x,y:d.center.z,fill:'#e7e0ce','font-size':9,'text-anchor':'middle'});label.textContent=d.id;groups.append(label)});document.querySelector('#path').setAttribute('points',p.map(q=>q.position.x+','+q.position.z).join(' '));document.querySelector('#player').setAttribute('cx',x);document.querySelector('#player').setAttribute('cy',z);state.textContent=JSON.stringify({preset:r.name,timeSeconds:+(t/1000).toFixed(1),circuit:a.cycle+1,camera:a.mode,active:a.active,loaded:a.loaded,npcTiers:a.tiers,position:{x:+x.toFixed(1),z:+z.toFixed(1)}},null,2)}
slider.oninput=()=>{playhead=+slider.value;show()};select.onchange=()=>{playhead=0;show()};document.querySelector('#reset').onclick=()=>{playing=false;document.querySelector('#play').textContent='Play';playhead=0;show()};document.querySelector('#play').onclick=()=>{playing=!playing;document.querySelector('#play').textContent=playing?'Pause':'Play';last=performance.now()};function frame(now){if(playing){playhead+=Math.min(100,now-last)*35;if(playhead>=+slider.max){playhead=+slider.max;playing=false;document.querySelector('#play').textContent='Play'}show()}last=now;requestAnimationFrame(frame)}show();requestAnimationFrame(frame);</script></html>`);
console.log(JSON.stringify({path:`${root}/${paths.output}`,images:imageRecords.length+1,referenceImages:1,videos:motion.clips.length,source:source.sha256}));
